# Generated by Django 5.1.7 on 2025-03-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0002_purchaserequest_purchasereceived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceived',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasereceived',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='purchasereceived',
            name='purchasepath',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.AddField(
            model_name='purchasereceived',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received')], default='pending', max_length=10)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('purchasepath', models.CharField(blank=True, default='', max_length=30)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_by', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SunApp.purchaserequest')),
            ],
        ),
    ]
