# Generated by Django 5.1.7 on 2025-03-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0003_remove_purchasereceived_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered')], default='pending', max_length=10),
        ),
    ]
