# Generated by Django 5.1.7 on 2025-03-17 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0005_remove_purchasereceived_purchase_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
