# Generated by Django 5.1.7 on 2025-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0006_remove_purchaserequest_ordered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='worktag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
